name = "ECCO"
uuid = "485acfd6-c8ad-4ff9-b233-a5c7cab2dfb0"
authors = ["gaelforget <gforget@mit.edu> and contributors"]
version = "0.0.1"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
